id: "cellar-crawl"
version: "1.0.0"
title: "Cellar Crawl"
format: "sugarcube-2.31.1"
description: "Explore the dark cellar beneith a creepy house to discover its secret."
header:
  - "shared/analytics/header/analytics.html"
  - "example-game/**/header/**/*"
deps:
  - "example-game/src"
